Dependencies upgrade
niksy/stylelint-no-restricted-syntax pull request #1
Opened 2021-08-23 06:39 UTC by vyobukhov

### Updated
- **BREAKING** Minimum Node.js version required is 10
- Upgraded dependencies
	- Upgraded stylelint to v13
	- Upgraded postcss-query-ast to v2
### Internal
- Replaced Mocha tests with Jest

2021-08-25 06:27 UTC, niksy requested changes

2021-08-25 06:27 UTC, niksy commented on package.json
> +    "stylelint": "^13.13.1"
@vyobukhov this could be peer dependancy since Stylelint plugin can’t work without Stylelint anyways

2021-08-25 06:27 UTC, niksy commented on package.json
> +  "jest": {
@vyobukhov why do we need Jest? I don’t recall that Stylelint forces testing library. See how I did it in one of my [recent plugins](https://github.com/niksy/stylelint-no-unresolved-module/blob/master/test/util/index.js)

2021-08-25 06:27 UTC, niksy commented
@vyobukhov Thanks for the changes! I’ve added some comments so please review them before we can merge this.

2021-08-25 06:28 UTC, niksy requested changes

2021-08-25 06:28 UTC, niksy commented on package.json
> +  "version": "2.0.0",
@vyobukhov this will be changed automatically with release process

2021-11-07 11:42 UTC, igoradamenko commented
@niksy, hey there!

Would you mind to merge and release this PR? 

Or maybe I can help you somehow with this process?

2021-11-07 15:46 UTC, niksy commented
@igoradamenko this is already done in latest version so I’m going to close this PR.

2021-11-07 15:46 UTC, closed without merging

2021-11-07 16:29 UTC, igoradamenko commented
Ah, lol, you're right. I haven't checked the latest version prior to writing this comment 🤦 

Thank you!